import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Button } from "../components/Button/Button";
import { ImageButton } from "../components/Button/ImageButton";
import { CardContainer } from "../components/CardContainer";
import { Chips } from "../components/ChipContainer";
import { SearchInput } from "../components/Input/SearchInput";
import styles from "../styles/Home.module.css";

const TotalShow: NextPage = () => {
  const chipData = [
    {
      key: 0,
      label: "TEST1",
      isSelected: false,
    },
    {
      key: 1,
      label: "Selected TEST",
      isSelected: true,
    },
    {
      key: 2,
      label: "TEST1",
      isSelected: false,
    },
    {
      key: 3,
      label: "Selected TEST",
      isSelected: true,
    },
    {
      key: 4,
      label: "TEST1",
      isSelected: false,
    },
    {
      key: 5,
      label: "Selected TEST",
      isSelected: true,
    },
    {
      key: 6,
      label: "TEST1",
      isSelected: false,
      backgroundColor: "red",
    },
    {
      key: 7,
      label: "Selected TEST",
      isSelected: true,
    },
    {
      key: 8,
      label: "TEST1",
      isSelected: false,
    },
    {
      key: 9,
      label: "Selected TEST",
      isSelected: true,
    },
    {
      key: 10,
      label: "TEST1",
      isSelected: false,
    },
    {
      key: 11,
      label: "Selected TEST",
      isSelected: true,
    },
  ];

  const cardData = [
    {
      key: 0,
      title: "TEST1",
      width: "160px",
      height: "160px",
      imgUrl: "/assets/example.svg",
    },
    {
      key: 1,
      title: "TEST 2",
      width: "160px",
      height: "160px",
      imgUrl: "/assets/example.svg",
    },
    {
      key: 2,
      title: "TEST 3",
      width: "160px",
      height: "160px",
      imgUrl: "/assets/example.svg",
    },
    {
      key: 3,
      title: "TEST 4",
      width: "160px",
      height: "160px",
      imgUrl: "/assets/example.svg",
    },
  ];
  return (
    <>
      {" "}
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {/* <Image
            src="/assets/main.svg"
            width="284px"
            height="284px"
            alt="title"
          /> */}
          <SearchInput></SearchInput>
          <h1> 태그 </h1>
          <Chips chipData={chipData}></Chips>
          <h1> 난이도 </h1>
          <h1> 체위 전체 보기 </h1>
          <h2> 체위 260개 결과 값 </h2>
          <CardContainer cardData={cardData}></CardContainer>

          <Link href="/">
            <Button
              labelText="랜덤 뽑기"
              height={120}
              width={368}
              padding={20}
              backgroundColor="#7B42AD"
              color="white"
            ></Button>
          </Link>
          <Link href="/">
            <Button
              labelText="메인 화면으로 "
              height={120}
              width={368}
              padding={20}
              backgroundColor="#32154B"
              color="white"
            ></Button>
          </Link>
        </main>

        <footer className={styles.footer}>Footer 공간</footer>
      </div>
    </>
  );
};

export default TotalShow;
